/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DeptDialog: typeof import('./src/components/Dialog/components/dept-dialog.vue')['default']
    Dialog: typeof import('./src/components/Dialog/index.vue')['default']
    Echarts: typeof import('./src/components/Echarts/index.vue')['default']
    FileIcon: typeof import('./src/components/FormItem/fileIcon.vue')['default']
    Form: typeof import('./src/components/Form/index.vue')['default']
    FormItem: typeof import('./src/components/FormItem/index.vue')['default']
    Icon: typeof import('./src/components/Icon/index.vue')['default']
    IconSelector: typeof import('./src/components/Icon/iconSelector.vue')['default']
    Outlet: typeof import('./src/components/Page/outlet.vue')['default']
    Page: typeof import('./src/components/Page/index.vue')['default']
    Pagination: typeof import('./src/components/Table/components/pagination.vue')['default']
    Region: typeof import('./src/components/FormItem/region.vue')['default']
    RichText: typeof import('./src/components/FormItem/richText.vue')['default']
    RoleDialog: typeof import('./src/components/Dialog/components/role-dialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Table/components/search.vue')['default']
    SvgIcon: typeof import('./src/components/Icon/svgIcon.vue')['default']
    Table: typeof import('./src/components/Table/index.vue')['default']
    Upload: typeof import('./src/components/FormItem/upload.vue')['default']
  }
}
